.TH RELAY-CARD 1 "August 30th, 2019" "version 0.1" "Control Waveshare Relay Board on Raspberry Pi 3B+"
.SH NAME
relay-card \- control Waveshare RPi Relay Board on Raspberry Pi 3B+
.SH SYNOPSIS
.B relay-card
.RB [ init | flash | on | off | reset ]
.RB [ 1 | 2 | 3 ]
.SH DESCRIPTION
The command relay-card is used to control the
Waveshare RPi Relay Board
on a Raspberry Pi 3B+.
The GPIOs controling the relay board are enabled by the relay-card systemd
service.
.PP
To use the relay-card command you must be member of the group dialout.
.TP
.B init
sets the relay GPIOs to output and switches the relays off.
This option is used by the systemd service.
.TP
.B flash
switches relay on for 1 second and off again.
.TP
.B on
switches relay on.
.TP
.B off
switches relay off.
.TP
.B reset
switches relay off for 3 seconds and on again.
.TP
.B status
displays the status of the 3 relays.
.SH AUTHOR
Heinrich Schuchardt <xypron.glpk@gmx.de>
